### ISSUE TITLE
Upload form shows "This published record has no files. You must create a new version to add, modify or delete files." but there is a file.

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/knowledge-commons-works#657]
User is trying to update the metadata on his deposit, but though there is a file visible in the viewer on the detail page he's getting the error in the title. He doesn't want to create another version at this point. The detail page is here: https://works.hcommons.org/records/zxz2c-7w076 but if you go here it says no file: https://works.hcommons.org/uploads/zxz2c-7w076?depositFormPage=page-6

<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzJuQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--767fc4224e200acb70eceb105004e8caf91d00d3/KC%20SC.jpg" alt="KC SC.jpg" />

**Comment by monotasker** [comment]
This is a strange one and I can't replicate the behaviour for edits to published records. The problem was that somehow a draft was created with no records attached (which I can't replicate), and since it's a draft of a published record the UI doesn't allow for fixing this. 

What I was able to do to free up the record, though, is click "discard changes" on the last page of the upload form. That cleared the corrupted draft and it looks like when you click "edit" on the record the files show up as expected.

So let's see whether they also can move forward and, if so, I'd suggest closing this one.

**Comment by bjr70** [comment]
Confirmed fixed by user.
